# Configuration for backbone process


backbone:
  # Run process on a separate thread
  thread: true

  # Apply the result to a mask instead
  mask: true

  # Allow process to run on background
  background: true

  # Save process result
  save:
    # Save folder
    path: C:/Tuan/GitHub/Human-Activity-Recognition/records

    # Save frequency (second)
    interval: 1
